### ISSUE TITLE
Display domain enums

### ISSUE THREAD

**Issue by ottworks** [jaxter184/bwEdit-Python#8]
![image](https://user-images.githubusercontent.com/5253130/38888059-6c8dafdc-422f-11e8-92db-a97ee8d2a324.png)

Find out and display what the domain numbers mean

**Comment by jaxter184** [comment]
lol i have no clue what they mean, but I do have the names for all the unit numbers, so I'll put those in for now

**Comment by jaxter184** [comment]
not sure about two of the domains (domain #2&5) but i've included their equations.
